week_5/Brian_code_CRUD/config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # resources :users
  
  
  get '/users', to: 'users#index'
  post '/users', to: 'users#create'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  get '/users/:id', to: 'users#show', as: 'user'
  put '/users/:id', to: 'users#update'
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'
  

  get '/welcome', to: 'welcome#index'
  get '/welcome/contact', to: 'welcome#contact', as: 'contact'
  get 'welcome/about'

  # You can have the root of your site routed with "root"
  root 'home#index'

  # the first part of the destination string is the controller
  # the second part is the action
  get '/awesome' => 'home#awesome'

  # alternate syntax
  get '/hello', to: 'home#hello'
end

week_5/Brian_code_CRUD/app/models/user.rb
class User < ActiveRecord::Base
end

week_5/Brian_code_CRUD/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week_5/Brian_code_CRUD/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@message = "I love NYCDA!"
	end

	def awesome
	end

end

week_5/Brian_code_CRUD/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	@user = User.find_by(email: params[:email])
  	if @user and @user.password == params[:password]
  		session[:user_id] = @user.id
  		flash[:notice] = "Succesfully logged in."
  		redirect_to @user
  	else
  		flash[:alert] = "Incorrect password or email."
  		render :new
  	end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out."
    redirect_to root_path
  end
end

week_5/Brian_code_CRUD/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def show
  end

  def edit
  end

  def create
  	@user = User.create(user_params)
  	flash[:notice] = "New account created"
  	redirect_to user_path(@user)
  end

  def update
  	@user.update(user_params)
  	flash[:notice] = "Profile updated"
  	redirect_to user_path(@user)
  end

  def destroy
  	@user.destroy
  	flash[:notice] = "User was deleted."
  	redirect_to users_path
  end

  private

  def set_user
  	@user = User.find(params[:id])
  end

  def user_params
  	params.require(:user).permit(:name, :email, :password)
  end
end

week_5/Brian_code_CRUD/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end
end

week_5/Brian_code_CRUD/app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
		session[:user_id] ? User.find(session[:user_id]) : nil
	end
end

week_5/Brian_code_CRUD/app/helpers/users_helper.rb
module UsersHelper
end

week_5/Brian_code_CRUD/app/helpers/welcome_helper.rb
module WelcomeHelper
end

week_5/Brian_code_CRUD/app/views/home/awesome.html.erb
<h1>This page is awesome.</h1>

week_5/Brian_code_CRUD/app/views/home/index.html.erb
<h1>Hello World!</h1>
<p><%= @message %></p>

week_5/Brian_code_CRUD/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloWorld</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<h3>Hello <%= current_user.name if current_user %></h3>
		<nav>
			<ul>
				<li><%= link_to 'home', root_path %></li>
				<li><%= link_to 'awesome', awesome_path %></li>
				<li><%= link_to 'users', users_path %></li>
				<% if current_user %>
					<li><%= link_to 'logout', logout_path, method: :delete %></li>
				<% else %>
					<li><%= link_to 'sign up', new_user_path %></li>
					<li><%= link_to 'login', login_path %></li>
				<% end %>
			</ul>
		</nav>	
	</header>	
	<main>
		<%= flash[:notice] if flash[:notice] %>
		<%= flash[:alert] if flash[:alert] %>
	 	<%= yield %>
	</main>
</body>
</html>

week_5/Brian_code_CRUD/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.email_field :email %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

week_5/Brian_code_CRUD/app/views/users/edit.html.erb
<h1>Edit your profile below!</h1>
<%= render 'form' %>

week_5/Brian_code_CRUD/app/views/users/index.html.erb
<h1>Listing Users</h1>
<p>Below is a list of all of our users:</p>
<ol>
	<% @users.each do |user| %>
		<li><%= link_to user.name, user_path(user.id) %></li>
	<% end %>
</ol>

week_5/Brian_code_CRUD/app/views/users/new.html.erb
<h1>Sign up below!</h1>

<%= render 'form' %>

week_5/Brian_code_CRUD/app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= link_to 'delete user', user_path(@user.id), method: :delete %></p>