week_5/first_app/config/routes.rb
Rails.application.routes.draw do
 

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # resources :users
  # get '/users' to: 'users#index'

  

  get '/users', to: 'users#index'
  post '/users', to: 'users#create'  
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  get '/users/:id', to: 'users#show', as: 'user'
  put '/users/:id', to: 'users#update'
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  root 'home#index'
  

 

  get 'welcome/index'

  get 'welcome/contact'

  get 'welcome/about'

  get '/awesome', to: 'home#hello'

  
end

week_5/first_app/app/models/tran.rb
class Tran < ActiveRecord::Base

	belongs_to: user
end

week_5/first_app/app/models/user.rb
class User < ActiveRecord::Base

	has_many :trans
	
end

week_5/first_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week_5/first_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def awesome
  	
  end
end

week_5/first_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	@user = User.find_by(email: params[:email])
  	if @user and @user.password == params[:password]
  		session[:user_id] = @user.user_id
  		flash[:notice] = "sucessfully logged in"
  		redirect_to user_path(@user)
  	else
  		flash[:aler] = "incorrect password or email"
  		render :new
  end

  def destroy
  	session
  	
  end
end

week_5/first_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
  	@users = User.all
  end

  def new
    @user = User.new
  end

  def show
  end

  def edit
  end

  def create
    @user = User.create(user_params)
    flash[:notice] = "New Account Created"
    redirect_to users_index_path
  end

  def update
    @user.update(user_params)
    flash[:notice] = "profile updated"
    redirect_to users_index_path(@user)
  end

  def destroy
  	@user.destroy
  	flash[:notice] = "user was deleted."
  	redirect_to users_index_path
  end

  def create
  	User.create
  end

  private

    def set_user
        @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

week_5/first_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end
end

week_5/first_app/app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		session[:user_id] ? User.find(session[session_id]) : nil	
	end
end

week_5/first_app/app/helpers/home_helper.rb
module HomeHelper
end

week_5/first_app/app/helpers/users_helper.rb
module UsersHelper
end

week_5/first_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

week_5/first_app/app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>My document</title>

<%= stylesheet_link_tag 'application', :cache => true %>
<%= javascript_include_tag :all, :cache => true %>
</head>
<body>

<%= link_to "users index", users_index_path %>


   
	
</body>
</html>

week_5/first_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h2>hello <%= current_user.name if current_user %></h2>

<nav>
	<ul>
		<li><%= link_to "home", root_path(@parent, @child) %></li>
		<li><%= link_to 'users', users_path %></li>
		<% if current_user %>
			<li><%= link_to 'logout', logout_path, method: :delete %></li>
		<% else %>
			<li><%= link_to 'signup', new_user_path %></li>
			<li><%= link_to 'login', login_path %></li>	
		<% end %>
	</ul>
</nav>
<div>
	<%= flash[:notice] if flash[:notice] %>
	<%= flash[:alert] if flash[:alert] %>
</div>

<%= yield %>

</body>
</html>

week_5/first_app/app/views/users/_form.html.erb
<h1>Edit your profile</h1>

<%= form_for (@user) do |f| %>
  
<p>
	<%= f.label :name %>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :email %>
	<%= f.email_field :email %>
</p>
<p>
	<%= f.label :password %>
	<%= f.password_field :password %>
</p>
	<%= f.submit %>
<% end %>

week_5/first_app/app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

week_5/first_app/app/views/users/index.html.erb
<h1>Users#index</h1>

<ol>
	<% @users.each do |user| %>
		
	<li><%= link_to user.name, user_path(user.id) %></li>
		
	<% end %>

</ol>

<p>Find me in app/views/users/index.html.erb</p>

week_5/first_app/app/views/users/new.html.erb
<h1>sign new below/h1>

<%= form_tag('/sessions', method: :post) do %>
<p>
	<%= label_tag :email %>
	<%= email_field_tag %>
</p>

<p>
	<%= label_tag :password %>
	<%= password_field_tag :password %>
</p>
<%= submit_tag %>
<% end %>


<%= render 'form' %>
   

week_5/first_app/app/views/users/show.html.erb
<h1>Users#show</h1><p></p>


<p> <%= link_to "delete user", user_path(@user.id), method: :delete %>

</p>

week_5/first_app/app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

week_5/first_app/app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

week_5/first_app/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>